version: "3"

services:
  frontend:
    image: docker.io/dgin/apache:v2
    volumes:
      - ./frontend:/var/www/html
      - ./configs/frontend/httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      - "8080:80"

  backend:
    image: docker.io/dgin/backend_rhel:v1
    volumes:
      - ./backend:/var/www/html
      - ./configs/backend/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./configs/backend/php.ini:/etc/php.ini
    ports:
      - "8081:80"
